### ISSUE TITLE
Unable to install npm package

### ISSUE THREAD

**Issue by apgapg** [jcalixte/vue-pwa-asset-generator#5]
Unable to install this package Linux Mint 19.3

```
master@master:~/WebProjects/vue-portfolio$ sudo npm install --global vue-pwa-asset-generator
loadDep:yargs → get       ▄ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:yargs → etag      ▄ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:tunnel-agent → ge ▐ ╢███████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:tunnel-agent → 30 ▐ ╢███████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:readable-stream → ▀ ╢██████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine decompress-response@6.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:mimic-response →  ▀ ╢██████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine chownr@2.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/bin/vue-asset-generate -> /usr/local/lib/node_modules/vue-pwa-asset-generator/script/index.js

> sharp@0.25.4 install /usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/master/.npm/_libvips/libvips-8.9.1-linux-x64.tar.gz
prebuild-install WARN This package does not support N-API version undefined 
prebuild-install WARN install EACCES: permission denied, access '/home/master/.npm'
make: Entering directory '/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/sharp/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a
  COPY Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:22:0:
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi.h:1939:33: error: ‘napi_callback_scope’ has not been declared
     CallbackScope(napi_env env, napi_callback_scope scope);
                                 ^~~~~~~~~~~~~~~~~~~
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi.h:1946:14: error: expected type-specifier before ‘napi_callback_scope’
     operator napi_callback_scope() const;
              ^~~~~~~~~~~~~~~~~~~
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi.h:1952:5: error: ‘napi_callback_scope’ does not name a type; did you mean ‘napi_callback_info’?
     napi_callback_scope _scope;
     ^~~~~~~~~~~~~~~~~~~
     napi_callback_info
In file included from /usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi.h:2426:0,
                 from ../src/common.cc:22:
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi-inl.h:4009:17: error: ‘napi_callback_scope’ has not been declared
   napi_env env, napi_callback_scope scope) : _env(env), _scope(scope) {
                 ^~~~~~~~~~~~~~~~~~~
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi-inl.h: In constructor ‘Napi::CallbackScope::CallbackScope(napi_env, int)’:
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi-inl.h:4009:57: error: class ‘Napi::CallbackScope’ does not have any field named ‘_scope’
   napi_env env, napi_callback_scope scope) : _env(env), _scope(scope) {
                                                         ^~~~~~
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi-inl.h: In constructor ‘Napi::CallbackScope::CallbackScope(napi_env, napi_async_context)’:
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi-inl.h:4015:41: error: ‘_scope’ was not declared in this scope
       _env, Object::New(env), context, &_scope);
                                         ^~~~~~
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi-inl.h:4015:41: note: suggested alternative: ‘bcopy’
       _env, Object::New(env), context, &_scope);
                                         ^~~~~~
                                         bcopy
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi-inl.h:4014:24: error: ‘napi_open_callback_scope’ was not declared in this scope
   napi_status status = napi_open_callback_scope(
                        ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi-inl.h:4014:24: note: suggested alternative: ‘napi_open_handle_scope’
   napi_status status = napi_open_callback_scope(
                        ^~~~~~~~~~~~~~~~~~~~~~~~
                        napi_open_handle_scope
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi-inl.h: In destructor ‘virtual Napi::CallbackScope::~CallbackScope()’:
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi-inl.h:4020:56: error: ‘_scope’ was not declared in this scope
   napi_status status = napi_close_callback_scope(_env, _scope);
                                                        ^~~~~~
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi-inl.h:4020:56: note: suggested alternative: ‘bcopy’
   napi_status status = napi_close_callback_scope(_env, _scope);
                                                        ^~~~~~
                                                        bcopy
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi-inl.h:4020:24: error: ‘napi_close_callback_scope’ was not declared in this scope
   napi_status status = napi_close_callback_scope(_env, _scope);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi-inl.h:4020:24: note: suggested alternative: ‘napi_close_handle_scope’
   napi_status status = napi_close_callback_scope(_env, _scope);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~
                        napi_close_handle_scope
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi-inl.h: At global scope:
/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/node-addon-api/napi-inl.h:4026:32: error: expected type-specifier before ‘napi_callback_scope’
 inline CallbackScope::operator napi_callback_scope() const {
                                ^~~~~~~~~~~~~~~~~~~
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
sharp.target.mk:123: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 5.4.0-37-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/vue-pwa-asset-generator/node_modules/sharp
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
/usr/local/lib
└── (empty)

npm ERR! Linux 5.4.0-37-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--global" "vue-pwa-asset-generator"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.25.4 install: `(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.25.4 install script '(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/master/WebProjects/vue-portfolio/npm-debug.log
npm ERR! code 1
master@master:~/WebProjects/vue-portfolio$ 
```

**Comment by jcalixte** [comment]
Hi @apgapg, it seems the lib used for cropping the images is compatible with node with the version `>= 10`. Is it possible for you to upgrade node?

I'll add the `engines` attribute in the package.json to be explicite. I'm sorry I can not be more helpful in your issue.
